
services:
  app:
    container_name: home-library-app
    image: koseckaya/nodejs-service:latest
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    networks:
      - home-library-network
    restart: unless-stopped
    command: npm run start:dev

  postgres:
    container_name: home-library-db
    image: postgres:15-alpine
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - home-library-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  volumes:
    postgres_data:

  networks:
    home-library-network:
      driver: bridge 